name: "Test"
on:
  push: {}
  workflow_dispatch: {}

jobs:
  run-test:
    name: "Run"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Call
        working-directory: ./sub/project-root
        run: javac Example.java
